---
sections:
  - label: Marketing Pages
    name: marketingPages
    path: content/marketing-pages
    templates:
      - simplePage
      - landingPage
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
