fragment PostParts on Post {
  title
  heroImg
  excerpt
  author {
    ... on Document {
      id
    }
  }
  date
  _body
}

fragment GlobalParts on Global {
  header {
    __typename
    icon {
      __typename
      color
      style
      name
    }
    color
    nav {
      __typename
      href
      label
    }
  }
  footer {
    __typename
    color
    social {
      __typename
      facebook
      twitter
      instagram
      github
    }
  }
  theme {
    __typename
    color
    font
    icon
    darkMode
  }
}

fragment AuthorParts on Author {
  name
  avatar
}

fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksHero {
      tagline
      headline
      text
      actions {
        __typename
        label
        type
        icon
        link
      }
      image {
        __typename
        src
        alt
      }
      color
    }
    ... on PageBlocksFeatures {
      items {
        __typename
        icon {
          __typename
          color
          style
          name
        }
        title
        text
      }
      color
    }
    ... on PageBlocksContent {
      body
      color
    }
    ... on PageBlocksTestimonial {
      quote
      author
      color
    }
  }
}
