// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: any }> = { [K in keyof T]: T[K] };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
  JSONObject: any;
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  sys?: Maybe<SystemInfo>;
  id: Scalars['ID'];
};

export type FormField = {
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};




export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename?: Maybe<Scalars['String']>;
  basename?: Maybe<Scalars['String']>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars['String']>>>;
  path?: Maybe<Scalars['String']>;
  relativePath?: Maybe<Scalars['String']>;
  extension?: Maybe<Scalars['String']>;
  template?: Maybe<Scalars['String']>;
  section?: Maybe<Section>;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars['Boolean']>;
};

export type Section = {
  __typename?: 'Section';
  type?: Maybe<Scalars['String']>;
  path?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  create?: Maybe<Scalars['String']>;
  match?: Maybe<Scalars['String']>;
  new_doc_ext?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['String']>>>;
  slug?: Maybe<Scalars['String']>;
  documents?: Maybe<Array<Maybe<Document>>>;
};

export type SectionDocumentUnion = MarketingPages_Document;

export type SectionParams = {
  marketingPages?: Maybe<MarketingPages_Input>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument?: Maybe<Document>;
  updateDocument?: Maybe<SectionDocumentUnion>;
  updateMarketingPagesDocument?: Maybe<MarketingPages_Document>;
};


export type MutationAddPendingDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  section?: Maybe<Scalars['String']>;
  template?: Maybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<SectionParams>;
};


export type MutationUpdateMarketingPagesDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<MarketingPages_Input>;
};

export type Query = {
  __typename?: 'Query';
  node?: Maybe<Node>;
  getDocument?: Maybe<SectionDocumentUnion>;
  getSections?: Maybe<Array<Maybe<Section>>>;
  getSection?: Maybe<Section>;
  getMarketingPagesDocument?: Maybe<MarketingPages_Document>;
  getMarketingPagesList?: Maybe<Array<Maybe<MarketingPages_Document>>>;
};


export type QueryNodeArgs = {
  id: Scalars['ID'];
};


export type QueryGetDocumentArgs = {
  section?: Maybe<Scalars['String']>;
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetSectionArgs = {
  section?: Maybe<Scalars['String']>;
};


export type QueryGetMarketingPagesDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};

export type MarketingPages_Data = SimplePage_Doc_Data | LandingPage_Doc_Data;

export type MarketingPages_Input = {
  simplePage?: Maybe<SimplePage_Doc_Input>;
  landingPage?: Maybe<LandingPage_Doc_Input>;
};

export type MarketingPages_Values = SimplePage_Doc_Values | LandingPage_Doc_Values;

export type MarketingPages_Form = SimplePage_Doc_Form | LandingPage_Doc_Form;

export type MarketingPages_Document = Node & Document & {
  __typename?: 'MarketingPages_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<MarketingPages_Data>;
  values?: Maybe<MarketingPages_Values>;
  form?: Maybe<MarketingPages_Form>;
};

export type SimplePage_Doc_Data = {
  __typename?: 'SimplePage_Doc_Data';
  title?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
};

export type SimplePage_Doc_Values = {
  __typename?: 'SimplePage_Doc_Values';
  title?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type TextField = FormField & {
  __typename?: 'TextField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type TextareaField = FormField & {
  __typename?: 'TextareaField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type SimplePage_Doc_FormFieldsUnion = TextField | TextareaField;

export type SimplePage_Doc_Form = {
  __typename?: 'SimplePage_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<SimplePage_Doc_FormFieldsUnion>>>;
};

export type SimplePage_Doc_Input = {
  title?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
};

export type BlockCta_Data = {
  __typename?: 'BlockCta_Data';
  text?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type BlockHero_Data = {
  __typename?: 'BlockHero_Data';
  heading?: Maybe<Scalars['String']>;
  message?: Maybe<Scalars['String']>;
};

export type LandingPage_Blocks_Data = BlockCta_Data | BlockHero_Data;

export type LandingPage_Doc_Data = {
  __typename?: 'LandingPage_Doc_Data';
  title?: Maybe<Scalars['String']>;
  blocks?: Maybe<Array<Maybe<LandingPage_Blocks_Data>>>;
  _body?: Maybe<Scalars['String']>;
};

export type BlockCta_Values = {
  __typename?: 'BlockCta_Values';
  text?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type BlockHero_Values = {
  __typename?: 'BlockHero_Values';
  heading?: Maybe<Scalars['String']>;
  message?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type LandingPage_Blocks_Values = BlockCta_Values | BlockHero_Values;

export type LandingPage_Doc_Values = {
  __typename?: 'LandingPage_Doc_Values';
  title?: Maybe<Scalars['String']>;
  blocks?: Maybe<Array<Maybe<LandingPage_Blocks_Values>>>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type BlockCta_FormFieldsUnion = TextField;

export type BlockCta_Form = {
  __typename?: 'BlockCta_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<BlockCta_FormFieldsUnion>>>;
};

export type BlockHero_FormFieldsUnion = TextField | TextareaField;

export type BlockHero_Form = {
  __typename?: 'BlockHero_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<BlockHero_FormFieldsUnion>>>;
};

export type LandingPage_Blocks_BlocksFieldTemplates = {
  __typename?: 'LandingPage_Blocks_BlocksFieldTemplates';
  blockCta?: Maybe<BlockCta_Form>;
  blockHero?: Maybe<BlockHero_Form>;
};

export type LandingPage_Blocks_BlocksField = FormField & {
  __typename?: 'LandingPage_Blocks_BlocksField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<LandingPage_Blocks_BlocksFieldTemplates>;
};

export type LandingPage_Doc_FormFieldsUnion = TextField | LandingPage_Blocks_BlocksField | TextareaField;

export type LandingPage_Doc_Form = {
  __typename?: 'LandingPage_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<LandingPage_Doc_FormFieldsUnion>>>;
};

export type BlockCta_Input = {
  text?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type BlockHero_Input = {
  heading?: Maybe<Scalars['String']>;
  message?: Maybe<Scalars['String']>;
};

export type Blocks_Input = {
  blockCta?: Maybe<BlockCta_Input>;
  blockHero?: Maybe<BlockHero_Input>;
};

export type LandingPage_Doc_Input = {
  title?: Maybe<Scalars['String']>;
  blocks?: Maybe<Array<Maybe<Blocks_Input>>>;
  _body?: Maybe<Scalars['String']>;
};


