---
name: content
label: Content
fields:
  - type: textarea
    label: Body
    name: body
  - name: color
    label: Color
    type: select
    config:
      source:
        type: simple
      options:
        - value: default
          label: default
        - value: tint
          label: tint
        - value: primary
          label: primary
